name: hlsdl build

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build for macOS
        run: make

      - name: Download testfile
        run: ./hlsdl -b -o test.ts "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

      - name: Verify testfile
        run: echo "6bf11a9a4be02443d4790e43e6569a614128bad453c5cb327ec74031f6ea6382  test.ts" | shasum -a256 -c

      - name: Create macOS release
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0-macos
          release_name: Release v1.0 for macOS
          body: |
            Release of version 1.0 for macOS.
        # Upload macOS artifact
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: hlsdl-macos
          path: ./hlsdl

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt -y install libcurl4-openssl-dev libssl-dev

      - name: Build for Ubuntu
        run: make

      - name: Download testfile
        run: ./hlsdl -b -o test.ts "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

      - name: Verify testfile
        run: echo "6bf11a9a4be02443d4790e43e6569a614128bad453c5cb327ec74031f6ea6382  test.ts" | shasum -a256 -c

      - name: Create Ubuntu release
        id: create_release_ubuntu
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0-ubuntu
          release_name: Release v1.0 for Ubuntu
          body: |
            Release of version 1.0 for Ubuntu.
        # Upload Ubuntu artifact
      - name: Upload Ubuntu artifact
        uses: actions/upload-artifact@v2
        with:
          name: hlsdl-ubuntu
          path: ./hlsdl

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msys2-root: C:\msys64
          install: mingw-w64-x86_64-gcc make

      - name: Install dependencies
        run: pacman -S --noconfirm mingw-w64-x86_64-curl mingw-w64-x86_64-openssl

      - name: Build for Windows
        run: mingw32-make

      - name: Download testfile
        run: ./hlsdl -b -o test.ts "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

      - name: Verify testfile
        run: echo "6bf11a9a4be02443d4790e43e6569a614128bad453c5cb327ec74031f6ea6382  test.ts" | shasum -a256 -c

      - name: Create Windows release
        id: create_release_windows
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0-windows
          release_name: Release v1.0 for Windows
          body: |
            Release of version 1.0 for Windows.
        # Upload Windows artifact
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: hlsdl-window
