name: hlsdl build

on:
  workflow_dispatch:

jobs:
  
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install dependencies
        run: choco install -y make mingw

      - name: Build for Windows
        run: mingw32-make

      - name: Download testfile
        run: ./hlsdl -b -o test.ts "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

      - name: Verify testfile
        run: echo "6bf11a9a4be02443d4790e43e6569a614128bad453c5cb327ec74031f6ea6382  test.ts" | shasum -a256 -c

      - name: Create Windows release
        id: create_release_windows
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0-windows
          release_name: Release v1.0 for Windows
          body: |
            Release of version 1.0 for Windows.
        # Upload Windows artifact
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: hlsdl-windows
          path: ./hlsdl
